# Generated by Django 5.1.6 on 2025-03-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("autenticacion", "0002_rename_perfil_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                default="avatars/default.JPG", upload_to="avatars/"
            ),
        ),
    ]
