# Generated by Django 5.1.6 on 2025-03-03 01:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("autenticacion", "0006_alter_profile_avatar"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="bio",
            new_name="biografia",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="birth_date",
        ),
    ]
