# Generated by Django 5.1.6 on 2025-03-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="fecha_creacion",
            field=models.DateField(null=True),
        ),
    ]
