# Generated by Django 5.1.6 on 2025-03-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_curso_fecha_creacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curso",
            name="fecha_creacion",
            field=models.DateField(default=None, null=True),
        ),
    ]
